spring:
  data:
    mongodb:
      uri: mongodb://scalog:scalog_NB_$713!@210.22.22.150:2091/scalog
  datasource:
    name: test
    url: jdbc:mysql://192.168.173.95:3306/credit_server?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: runlion@123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 15
    initialSize: 3
    maxWait: 5000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 90000
    minEvictableIdleTimeMillis: 1800000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
scalog:
  level: all
  countryName: 中国
  groupName: 谷歌集团
  organizationName: 谷歌开源组织
  companyName: 谷歌杭州分公司
  projectName: 棱镜项目
  db: mysql
server:
  port: 1111
